

insert into dia_semana(dia_semana) values ('Segunda'), ('Terça'), ('Quarta'), ('Quinta'), ('Sexta'), ('Sábado'), ('Domingo');

insert into servico (servico, id_grupo_servico) VALUES ('Cauterização', 4), 
	('Luzes', 4), ('Mechas', 4), ('Escova', 5), ('Progressiva', 4), ('Progressiva Cabelos Curto', 4),
	('Progressiva Cabelos Médios', 4), ('Progressiva Cabelos Longos', 4), ('Nutrição', 4), ('Hidratação', 4),
	('Matização', 4), ('Coloração', 4),	('Tonalização', 4), ('Botox', 4), ('Baby Liss', 5), ('Mega Hair', 5),
	('Relaxamento', 4), ('Reconstrução',4),	('Cristalização', 4), ('Lavar c/ Secar', 5), ('Lavar s/ Secar', 5), 
	('Progressiva Masculina', 4), ('Luzes Mediterrane Curto', 4), ('Luzes Touca', 4), 
	('Aplicação de Ampola', 4), ('Mega Hair Redinha', 5), 	('Mega Hair Queratina', 5), 
	('Prancha', 5), ('Corte Masculino', 5), ('Corte Feminino', 5), ('Penteado', 5),
	('Corte Masculino com Lavagem', 5), ('Corte Feminino com Lavagem', 5), 
	('Pézinho', 5), ('Limpeza de Pele', 2), ('Tratamento Acne', 2), 
	('Depilação facial', 2), ('Hidratação facial', 2 ), 
	('Remoção de Manchas', 2),('Tratamento de olheiras', 2),('Rejuvenscimento', 2),
	('Lifting papada', 2),('Lifting facial', 2),('Lifting Corporal', 1),('Botox', 2),
	('Bioplastia', 2),('Peeling', 2),('Fios de Sustentação', 2),
	('Máscara Renovadora com Pepino', 2),('Máscara Hidratante com Iogurte', 2),
	('Máscara com clara de ovo', 2),('Máscara Esfoliante com Açúcar', 2),('Criolipólise', 1),
	('Lipocavitação', 1),('Carboxiterapia', 1),('Tratamentos de Depilação a Laser', 1),
	('Shiatsu', 3), ('Abhyanga', 3), ('Ayurvédica', 3), ('Relaxante', 3),
	('Reflexologia', 3),('Desportiva', 3),('Lâmina', 6), ('Cera quente', 6),
	('Cera fria', 6), ('Creme depilatório', 6), ('Depilação com Linha', 6),
	('Depilação a Laser', 6), ('Fotodepilação', 6), ('Depilação com luz pulsante', 6),
	('Maquiagem digital/HD', 7), ('Maquiagem Fotografia', 7), ('Maquiagem Rápida', 7), 
	('Maquiagem para Casamento', 7), ('Olhos para o dia', 7), ('Olhos esfumaçados', 7), ('Contorno e Iluminacao', 7), 
	('Cílios postiços', 7), ('Lábios perfeitos', 7), ('Deliniador', 7), ('Sobrancelhas', 7),
	('Sobrancelha de henna', 8), ('Sobrancelha na pinça', 8), (' Sobrancelha na cera', 8), 
	('Sobrancelha na linha', 8), ('Definitiva', 8), ('Tatuada', 8),
	('Pés ', 9), ('Mãos', 9), ('Mãos sem pintar', 9), ('Mãos decorada', 9), ('Pés e Mãos com decoração', 9),
	('Pés sem pintar', 9), ('Pés decorado', 9), ('Pés e Mãos', 9), ('Pés e Mãos sem pintar', 9);
	('Pés ', 10), ('Mãos', 10), ('Mãos sem pintar', 10), ('Mãos decorada', 10), 
	('Pés sem pintar', 10), ('Pés decorado', 10), ('Pés e Mãos', 10), ('Pés e Mãos sem pintar', 10),
	('Pés e Mãos com decoração', 10),	
	('Tratamento de unha encravada', 11), ('Tratamento de olho de peixe', 11),
	('Órtese', 11),	('Tratamento de Unha Encravada', 11),('Tratamento de Micose', 11),
	('Tratamento de Olho de Peixe', 11),('Tratamento Dos Pés', 11),
	('Tratamento para Pés de Diabéticos', 11),('Tratamento para Fissuras Nos Pés', 11),
	('Tratamento para Frieiras', 11),('Tratamento para Dor Nos Pés', 11),
	('Tratamento para Calosidades', 11), ('Tratamento para Pés Rachados', 11),
	('Tratamento para Pé de Atleta', 11), ('Tratamento para Fungos Nos Pés', 11);

